### ISSUE TITLE
Borderless mode doesn't work?

### ISSUE THREAD

**Issue by KainXVIII** [Lyall/SO4Fix#2]
So i enabled borderless mode and i still see borders when in windowed mode or when i alt-tabbed from game.

> [Custom Resolution]
; Forces a custom resolution. 
; Enabling borderless will make windowed mode borderless fullscreen.
Enabled = false
Width = 2560
Height = 1440
Borderless = true

![image](https://github.com/user-attachments/assets/63c29ba8-ad56-4cb6-87e3-3d383d5043ae)

**Comment by KainXVIII** [comment]
Seems like borderless mode is working..after you switch from FS to win mode several times!

**Comment by Lyall** [comment]
> Seems like borderless mode is working..after you switch from FS to win mode several times!

The game can be a bit finnicky with the window mode switching. It actually switches back to windowed mode if you alt+tab while in fullscreen. Borderless should work on every game startup so long as you have windowed mode set in-game, and if you're switching in-game you do have to go back and forth sometimes as you mentioned.

I've added a note to the known issues section referencing your solution and I'm glad you got it working!
